const ERROR_BAD_REQUEST = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_EMAIL = 409;
const ERROR_INTERNAL_SERVER = 500;

module.exports = {
  ERROR_BAD_REQUEST,
  ERROR_NOT_FOUND,
  ERROR_EMAIL,
  ERROR_INTERNAL_SERVER,
};
